jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - attach_workspace:
        at: /tmp/workspace
      - run: go build hello.go

  test:
    docker:
      - image: circleci/golang
    working_directory: /tmp
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace
      - run: go test
      - persist_to_workspace:
          root: /tmp/workspace
          paths: 
            - ./

workflows:
  version: 2
  test-build:
    jobs:
      - test
      - build:
          requires:
            - test