jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: /tmp/project
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
      - run: mkdir -p /tmp/workspace
      - run: go get github.com/lib/pq
      - run: go get github.com/gorilla/mux
      - run: sudo apt-get update && sudo apt-get install -y git netcat curl
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: go test
      - run: go build -o code/hello
      - persist_to_workspace:
          root: /tmp/project
          paths: 
            - ./
            - go/github.com/


  test:
    docker:
      - image: katalonstudio/katalon
      - image: circleci/postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: demotable
    working_directory: /tmp/project
    steps:
      - attach_workspace:
          at: /tmp/project
      - restore_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in 'seq 1 10';
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: seeding db
          command: |
            set PGPASSWORD=postgres
            sudo apt-get install -y postgresql-client
            psql --host localhost -U postgres < demotable.sql
      - run:
          name: Run server in background
          command: |
            ./code/hello
          background: true
      - run:
          name: Waiting for server to be ready
          command: |
            for i in 'seq 1 300';
            do
              nc -z 127.0.0.1 3500 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for server && exit 1
      - run:
          name: Katalon Test
          command: katalon-execute.sh -retry=0 -statusDelay=15 -testSuiteCollectionPath="demo/Test Suites/RegressionTest"
      - store_artifacts:
          path: code
      - store_artifacts:
          path: report

workflows:
  version: 2
  test-build:
    jobs:
      - build
      - test:
          requires:
            - build